server:
  port: 8081

spring:
  application:
    name: tasks

management:
  endpoints:
    web:
      exposure:
        include: health, tasks, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true