openapi: 3.0.3
info: 
    title: Сервис пользователя openAPI спецификация
    version: '0.0.1'
servers: 
  - url: 'http://localhost:8030/api/v1/'
    description: Dev server
paths:
  /auth/login:
    post:
      summary: Авторизация пользователя
      tags:
        - Authorization
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticateDto'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request

  /account/me:
    get:
      summary: Получение профиля пользователя по логину пользователя
      tags: 
       - Account
      operationId: getMyProfile
      parameters: 
        - name: login
          in: query
          required: true
          schema: 
            type: string
      responses:
        '200':
            description: Successful operation
            content: 
              application/json: 
                schema:
                  $ref: "#/components/schemas/PersonDto" 
        '400':
            description: Bad request
  /account/{id}:
    get:
      summary: Получение пользователя по идентификатору
      tags:
        - Account
      operationId: getPersonsById
      parameters: 
        - name: id
          in: path
          required: true
          schema: 
            type: string
      responses:
          '200':
              description: Successful operation
              content:
                  application/json: 
                    schema: 
                      $ref: "#/components/schemas/PersonDto"
          '400':
              description: Bad request

components:
    schemas:
      PersonDto:
        type: object
        description: Пользователь
        required:
          - firstName
          - lastName
        properties:
          id:
            type: string
            format: uuid
            description: ID пользователя
          userId:
            type: string
            format: uuid
            description: ID пользователя
          firstName:
            type: string
            description: Имя
          lastName:
            type: string
            description: Фамилия
          regDate:
            type: string
            description: Дата и время регистрации
            format: date-time
      AuthenticateDto:
            type: object
            properties:
              login:
                type: string
                description: Логин пользователя
              password:
                type: string
                description: Пароль пользователя
            description: DTO аутентификации