global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'database_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['database:8050']
        labels:
          application: 'Database Service'
  - job_name: 'profile_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'profile:8040' ]
        labels:
          application: 'Profile Service'
  - job_name: 'gateway_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8030']
        labels:
          application: 'Gateway Service'
  - job_name: 'tasks_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tasks:8081']
        labels:
          application: 'Tasks Service'